server {
    listen 80;
    server_name _;  # 后续换成您的域名

    location /static/ {
        alias /app/static/;
    }
    location /media/ {
        alias /app/media/;
    }
    location / {
        include uwsgi_params;
        uwsgi_pass django:8000;
    }
}