[uwsgi]
socket = :8000
chdir = /app
module = volunteer_project.wsgi:application
master = true
processes = 4
threads = 2
vacuum = true
buffer-size = 32768
static-map = /static=/app/static
static-map = /media=/app/media
die-on-term = true