# Generated by Django 6.0.2 on 2026-02-06 01:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱地址')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('purpose', models.CharField(choices=[('register', '注册'), ('login', '登录'), ('reset', '重置密码')], max_length=20, verbose_name='用途')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose'], name='volunteers__email_5dcb9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('unverified', '未认证'), ('volunteer', '志愿者'), ('organizer', '活动发布者'), ('admin', '管理员')], default='unverified', max_length=20, verbose_name='用户角色')),
                ('verification_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('needs_review', '需要补充资料')], default='pending', max_length=20, verbose_name='认证状态')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的中国大陆手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='手机号码')),
                ('id_card_number', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('current_address', models.TextField(verbose_name='现居住地址')),
                ('emergency_contact', models.CharField(max_length=50, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(max_length=11, verbose_name='紧急联系电话')),
                ('volunteer_experience', models.TextField(blank=True, verbose_name='志愿服务经历')),
                ('skills', models.TextField(blank=True, verbose_name='专业技能')),
                ('available_time', models.CharField(blank=True, max_length=100, verbose_name='可服务时间')),
                ('organization_name', models.CharField(blank=True, max_length=200, verbose_name='组织/机构名称')),
                ('organization_type', models.CharField(blank=True, choices=[('ngo', '非政府组织'), ('school', '学校'), ('company', '企业'), ('community', '社区组织'), ('government', '政府部门'), ('other', '其他')], max_length=50, verbose_name='组织类型')),
                ('organization_certificate', models.ImageField(blank=True, upload_to='certificates/%Y/%m/%d/', verbose_name='组织机构证明')),
                ('organization_description', models.TextField(blank=True, verbose_name='组织描述')),
                ('identity_document', models.ImageField(upload_to='identities/%Y/%m/%d/', verbose_name='身份证明文件')),
                ('additional_documents', models.JSONField(blank=True, default=list, verbose_name='附加证明文件')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_notes', models.TextField(blank=True, verbose_name='审核意见')),
                ('data_consent', models.BooleanField(default=False, verbose_name='数据使用同意')),
                ('last_data_access', models.DateTimeField(blank=True, null=True, verbose_name='上次数据访问时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profiles', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户详细资料',
                'verbose_name_plural': '用户详细资料',
            },
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view_profile', '查看用户资料'), ('export_data', '导出数据'), ('modify_data', '修改数据')], max_length=20, verbose_name='访问类型')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('reason', models.TextField(verbose_name='访问原因')),
                ('accessed_fields', models.JSONField(default=list, verbose_name='访问字段')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_accesses', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
                ('accessed_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='volunteers.userprofile', verbose_name='被访问用户')),
            ],
            options={
                'verbose_name': '数据访问日志',
                'verbose_name_plural': '数据访问日志',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', '提交认证'), ('approve', '通过认证'), ('reject', '拒绝认证'), ('request_update', '要求补充资料'), ('role_change', '角色变更')], max_length=20, verbose_name='操作类型')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('notes', models.TextField(blank=True, verbose_name='操作说明')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_actions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='volunteers.userprofile', verbose_name='用户资料')),
            ],
            options={
                'verbose_name': '认证日志',
                'verbose_name_plural': '认证日志',
                'ordering': ['-performed_at'],
            },
        ),
    ]
