# Generated by Django 6.0.2 on 2026-02-08 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_address',
            field=models.TextField(blank=True, null=True, verbose_name='现居住地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='紧急联系电话'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identity_document',
            field=models.ImageField(blank=True, null=True, upload_to='identities/%Y/%m/%d/', verbose_name='身份证明文件'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='请输入有效的中国大陆手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名'),
        ),
    ]
