# Generated by Django 6.0.2 on 2026-02-08 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_alter_userprofile_current_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('activity_type', models.CharField(choices=[('elderly', '敬老服务'), ('environment', '环境保护'), ('education', '教育支持'), ('medical', '医疗健康'), ('community', '社区服务'), ('other', '其他')], default='other', max_length=20, verbose_name='活动类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('address_detail', models.TextField(verbose_name='详细地址')),
                ('max_participants', models.PositiveIntegerField(verbose_name='最大参与人数')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='当前报名人数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('ongoing', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='活动状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否审核通过')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activities', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_activities', to='volunteers.userprofile', verbose_name='组织者')),
            ],
            options={
                'verbose_name': '志愿活动',
                'verbose_name_plural': '志愿活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='报名状态')),
                ('application_notes', models.TextField(blank=True, verbose_name='报名备注')),
                ('experience_expectation', models.TextField(blank=True, verbose_name='经验期望')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_notes', models.TextField(blank=True, verbose_name='审核意见')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteers.userprofile', verbose_name='志愿者')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteers.volunteeractivity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'ordering': ['-applied_at'],
                'unique_together': {('activity', 'volunteer')},
            },
        ),
    ]
