# Generated by Django 6.0.2 on 2026-02-09 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_announcement_guide_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='设置键')),
                ('value', models.TextField(verbose_name='设置值')),
                ('name', models.CharField(max_length=200, verbose_name='设置名称')),
                ('description', models.TextField(blank=True, verbose_name='设置描述')),
                ('category', models.CharField(choices=[('general', '常规设置'), ('security', '安全设置'), ('email', '邮件设置'), ('verification', '验证设置'), ('activity', '活动设置'), ('ui', '界面设置')], default='general', max_length=50, verbose_name='分类')),
                ('type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('boolean', '布尔值'), ('json', 'JSON对象'), ('text', '长文本')], default='string', max_length=20, verbose_name='值类型')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('is_editable', models.BooleanField(default=True, verbose_name='是否可编辑')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后更新者')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'ordering': ['category', 'key'],
            },
        ),
    ]
