# Generated by Django 6.0.2 on 2026-02-12 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_volunteeractivity_review_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', '提交审核'), ('approve', '通过'), ('reject', '拒绝'), ('need_review', '要求修改'), ('cancel', '取消活动'), ('publish', '发布')], max_length=20, verbose_name='操作')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='volunteers.volunteeractivity')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '活动审核日志',
                'verbose_name_plural': '活动审核日志',
                'ordering': ['-performed_at'],
            },
        ),
    ]
