# Generated by Django 6.0.2 on 2026-02-12 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_activityreviewlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityapplication',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='审批备注/拒绝理由'),
        ),
        migrations.AlterField(
            model_name='activityapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AlterField(
            model_name='activityapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='activityreviewlog',
            name='action',
            field=models.CharField(choices=[('submit', '提交审核'), ('approve', '通过'), ('reject', '拒绝'), ('need_review', '要求修改'), ('update', '更新'), ('publish', '发布'), ('cancel', '取消')], max_length=20, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='activityreviewlog',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='volunteers.volunteeractivity', verbose_name='关联活动'),
        ),
        migrations.AlterField(
            model_name='activityreviewlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_review_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reminder', '活动提醒'), ('change', '活动变更'), ('cancellation', '活动取消'), ('other', '其他通知')], default='other', max_length=20, verbose_name='通知类型')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='volunteers.volunteeractivity', verbose_name='关联活动')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
